loe_prompts:
    llm_system_role: |
        Instructions:
        You will receive job letter for an employee, please extract the following information and return it in JSON format as such: 
        {
            "employment_date": ((Start date of employment)),
            "salary": ((Yearly salary or hourly rate number)),
            "currency": ((Currency)),
            "compensation_type": ((Type of compensation, salary or hourly))
        }
        
        Example of a letter:
        John has been employed at Canada Post since January 25, 2010. He works an average of 40 hrs/week with a current annual salary of $65,000.00
        
        Example of a valid response:
        {
            "employment_date": "25/01/2010",
            "salary": 65000.00,
            "currency": "CAD",
            "compensation_type": "salary"
        }
        
        Formatting notes:
        - Make sure the date is the starting date of employment or the day the employee was hired and not the date the letter was written 
        - Make sure to format the date as: DD/MM/YYYY
        - Make sure the salary is formatted as a float rounded to the nearest 2 decimals
        - Make sure the currency is in letters formatted in ISO standard. If not stated explicitly in the letter, assume the currency is from the country is operating from based on the located stated on the letter 
        - Make sure the type of compensation is stated only in the following lowercase strings 'salary' or 'hourly'. If both show up on the letter prioritize showing the yearly salary
        
        Letter:

payslip_prompts:
    regular_earnings_prompt: "You are provided with financial pay stubs. What is the Regular Salary? Provide the lower value between Regular and Gross Salary if applicable. 
    Terminology might differ. Regular earnings refer to earnings without any bonuses or benefits

    In the final response provide ONLY the numerical value of the Regular earnings."

    ytd_earnings_prompt: "You are provided with financial pay stubs. What is the Regular YTD earnings? Provide the lower value between Regular YTD and Gross YTD earnings if applicable. 
    Terminology might differ. Regular earnings refer to earnings without any bonuses or benefits

    In the final response provide ONLY the numerical value of the Regular YTD earnings."

    payment_date_prompt: "You are provided with the text extracted from financial pay stubs. Provide the start and end date of the pay stub in the following format DD/MM/YYYY as:\n
    (Start date) ; (End date)\n
    \n
    For example, for a pay stub that starts on March 1st, 2024 and ends on March 15th, 2024 the output should be:\n
    01/03/2024 ; 15/03/2024\n
    \n
    Directions:\n
    - The dates might not be clearly displayed, look for a word date and a number after it which may represent the date\n
    - If you cannot find both dates, go through and try to find them again\n
    - If you could only provide 1 date, provide that date. If you cannot find any dates, say that you could not find the dates.\n
    - Make sure you provide the start and end dates of the pay stub and not the payment period when the salary was paid, look for terminology resembling 'start' and 'end'\n
    \n
    Pay stub text:\n
    {text}\n
    \n
    Your response:\n
    "

    payment_date_prompt_csv: "You are provided with the tables extracted from financial pay stubs. Provide the start and end date of the pay stub in the following format DD/MM/YYYY as:
    (Start date) ; (End date)
    
    For example, for a pay stub that starts on March 1st, 2024 and ends on March 15th, 2024 the output should be:
    01/03/2024 ; 15/03/2024
    
    Notes:
    - If you cannot find both dates, go through and try to find them again
    - If you could only provide 1 date, provide that date. If you cannot find any dates, say that you could not find the dates.
    - Look for terminology resembling 'start' and 'end' such as 'beginning', or 'ending'
    "